// action types
export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const NAVIGATION = 'NAVIGATION';

export const SET_ALERT_STATUS = 'SET_ALERT_STATUS';
export const SET_ALERT_STATUS_SUCCESS = 'SET_ALERT_STATUS_SUCCESS';

export const SET_PRINT_AGREEMENT_STATUS = 'SET_PRINT_AGREEMENT_STATUS';
export const SET_PRINT_AGREEMENT_STATUS_SUCCESS = 'SET_PRINT_AGREEMENT_STATUS_SUCCESS';
export const SET_PRINT_AGREEMENT_STATUS_FAILURE = 'SET_PRINT_AGREEMENT_STATUS_FAILURE';

export const SET_LOGIN_RESPONSE_STATUS = 'SET_LOGIN_RESPONSE_STATUS';
export const SET_LOGIN_RESPONSE_STATUS_SUCCESS = 'SET_LOGIN_RESPONSE_STATUS_SUCCESS';
export const SET_LOGIN_RESPONSE_STATUS_FAILURE = 'SET_LOGIN_RESPONSE_STATUS_FAILURE';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// GET CALLS BELOW
export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAILURE = 'GET_COUNTRY_FAILURE';

export const GET_STATES = 'GET_STATES';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAILURE = 'GET_STATES_FAILURE';

export const GET_CITY = 'GET_CITY';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_FAILURE = 'GET_CITY_FAILURE';

export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const GET_VIEW_USERS        = 'GET_VIEW_USERS';
export const GET_VIEW_USERS_SUCCESS = 'GET_VIEW_USERS_SUCCESS';
export const GET_VIEW_USERS_FAILURE = 'GET_VIEW_USERS_FAILURE';

export const GET_USER_DATA        = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

export const GET_USER_TYPES = 'GET_USER_TYPES';
export const GET_USER_TYPES_SUCCESS = 'GET_USER_TYPES_SUCCESS';
export const GET_USER_TYPES_FAILURE = 'GET_USER_TYPES_FAILURE';

export const GET_VIEW_ROLES = 'GET_VIEW_ROLES';
export const GET_VIEW_ROLES_SUCCESS = 'GET_VIEW_ROLES_SUCCESS';
export const GET_VIEW_ROLES_FAILURE = 'GET_VIEW_ROLES_FAILURE';

export const GET_ROLE_DATA = 'GET_ROLE_DATA';
export const GET_ROLE_DATA_SUCCESS = 'GET_ROLE_DATA_SUCCESS';
export const GET_ROLE_DATA_FAILURE = 'GET_ROLE_DATA_FAILURE';

export const GET_EDIT_ROLE_DATA = 'GET_EDIT_ROLE_DATA';
export const GET_EDIT_ROLE_DATA_SUCCESS = 'GET_EDIT_ROLE_DATA_SUCCESS';
export const GET_EDIT_ROLE_DATA_FAILURE = 'GET_EDIT_ROLE_DATA_FAILURE';

export const GET_ADD_BULK_IMPORT = 'GET_ADD_BULK_IMPORT';
export const GET_ADD_BULK_IMPORT_SUCCESS = 'GET_ADD_BULK_IMPORT_SUCCESS';
export const GET_ADD_BULK_IMPORT_FAILURE = 'GET_ADD_BULK_IMPORT_FAILURE';

export const GET_VIEW_ORGANIZATIONS = 'GET_VIEW_ORGANIZATIONS';
export const GET_VIEW_ORGANIZATIONS_SUCCESS = 'GET_VIEW_ORGANIZATIONS_SUCCESS';
export const GET_VIEW_ORGANIZATIONS_FAILURE = 'GET_VIEW_ORGANIZATIONS_FAILURE';

export const GET_ORGANIZATION = 'GET_ORGANIZATION';
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';
export const GET_ORGANIZATION_FAILURE = 'GET_ORGANIZATION_FAILURE';

export const GET_ORGANIZATIONS_CHART = 'GET_ORGANIZATIONS_CHART';
export const GET_ORGANIZATIONS_CHART_SUCCESS = 'GET_ORGANIZATIONS_CHART_SUCCESS';
export const GET_ORGANIZATIONS_CHART_FAILURE = 'GET_ORGANIZATIONS_CHART_FAILURE';

export const GET_USER_TYPE_LIST = 'GET_USER_TYPE_LIST';
export const GET_USER_TYPE_LIST_SUCCESS = 'GET_USER_TYPE_LIST_SUCCESS';
export const GET_USER_TYPE_LIST_FAILURE = 'GET_USER_TYPE_LIST_FAILURE';

export const GET_ROLE_LIST = 'GET_ROLE_LIST';
export const GET_ROLE_LIST_SUCCESS = 'GET_ROLE_LIST_SUCCESS';
export const GET_ROLE_LIST_FAILURE = 'GET_ROLE_LIST_FAILURE';

export const GET_OFFICE_LIST = 'GET_OFFICE_LIST';
export const GET_OFFICE_LIST_SUCCESS = 'GET_OFFICE_LIST_SUCCESS';
export const GET_OFFICE_LIST_FAILURE = 'GET_OFFICE_LIST_FAILURE';

export const GET_DEPARTMENT_LIST = 'GET_DEPARTMENT_LIST';
export const GET_DEPARTMENT_LIST_SUCCESS = 'GET_DEPARTMENT_LIST_SUCCESS';
export const GET_DEPARTMENT_LIST_FAILURE = 'GET_DEPARTMENT_LIST_FAILURE';

export const GET_SEND_AGREEMENT = 'GET_SEND_AGREEMENT';
export const GET_SEND_AGREEMENT_SUCCESS = 'GET_SEND_AGREEMENT_SUCCESS';
export const GET_SEND_AGREEMENT_FAILURE = 'GET_SEND_AGREEMENT_FAILURE';

// POST CALLS BELOW
export const POST_EXPORT_USERS        = 'POST_EXPORT_USERS';
export const POST_EXPORT_USERS_SUCCESS = 'POST_EXPORT_USERS_SUCCESS';
export const POST_EXPORT_USERS_FAILURE = 'POST_EXPORT_USERS_FAILURE';

export const POST_SEARCH_ROLES        = 'POST_SEARCH_ROLES';
export const POST_SEARCH_ROLES_SUCCESS = 'POST_SEARCH_ROLES_SUCCESS';
export const POST_SEARCH_ROLES_FAILURE = 'POST_SEARCH_ROLES_FAILURE';

export const POST_SEARCH_USERS        = 'POST_SEARCH_USERS';
export const POST_SEARCH_USERS_SUCCESS = 'POST_SEARCH_USERS_SUCCESS';
export const POST_SEARCH_USERS_FAILURE = 'POST_SEARCH_USERS_FAILURE';

export const POST_REGISTER_DATA = 'POST_REGISTER_DATA';
export const POST_REGISTER_DATA_SUCCESS = 'POST_REGISTER_DATA_SUCCESS';
export const POST_REGISTER_DATA_FAILURE = 'POST_REGISTER_DATA_FAILURE';

export const POST_LOGIN_DATA = 'POST_LOGIN_DATA';
export const POST_LOGIN_DATA_SUCCESS = 'POST_LOGIN_DATA_SUCCESS';
export const POST_LOGIN_DATA_FAILURE = 'POST_LOGIN_DATA_FAILURE';

export const POST_FORGOT_PASSWORD = 'POST_FORGOT_PASSWORD';
export const POST_FORGOT_PASSWORD_SUCCESS = 'POST_FORGOT_PASSWORD_SUCCESS';
export const POST_FORGOT_PASSWORD_FAILURE = 'POST_FORGOT_PASSWORD_FAILURE';

export const POST_OTP_DATA = 'POST_OTP_DATA';
export const POST_OTP_DATA_SUCCESS = 'POST_OTP_DATA_SUCCESS';
export const POST_OTP_DATA_FAILURE = 'POST_OTP_DATA_FAILURE';

export const POST_RESET_PASSWORD = 'POST_RESET_PASSWORD';
export const POST_RESET_PASSWORD_SUCCESS = 'POST_RESET_PASSWORD_SUCCESS';
export const POST_RESET_PASSWORD_FAILURE = 'POST_RESET_PASSWORD_FAILURE';

export const POST_ADD_USER = 'POST_ADD_USER';
export const POST_ADD_USER_SUCCESS = 'POST_ADD_USER_SUCCESS';
export const POST_ADD_USER_FAILURE = 'POST_ADD_USER_FAILURE';

export const POST_ADD_ROLE = 'POST_ADD_ROLE';
export const POST_ADD_ROLE_SUCCESS = 'POST_ADD_ROLE_SUCCESS';
export const POST_ADD_ROLE_FAILURE = 'POST_ADD_ROLE_FAILURE';

export const POST_EDIT_USER = 'POST_EDIT_USER';
export const POST_EDIT_USER_SUCCESS = 'POST_EDIT_USER_SUCCESS';
export const POST_EDIT_USER_FAILURE = 'POST_EDIT_USER_FAILURE';

export const POST_EDIT_ROLE = 'POST_EDIT_ROLE';
export const POST_EDIT_ROLE_SUCCESS = 'POST_EDIT_ROLE_SUCCESS';
export const POST_EDIT_ROLE_FAILURE = 'POST_EDIT_ROLE_FAILURE';

export const POST_ADD_BULK_IMPORT = 'POST_ADD_BULK_IMPORT';
export const POST_ADD_BULK_IMPORT_SUCCESS = 'POST_ADD_BULK_IMPORT_SUCCESS';
export const POST_ADD_BULK_IMPORT_FAILURE = 'POST_ADD_BULK_IMPORT_FAILURE';

export const POST_ADD_OFFICE = 'POST_ADD_OFFICE';
export const POST_ADD_OFFICE_SUCCESS = 'POST_ADD_OFFICE_SUCCESS';
export const POST_ADD_OFFICE_FAILURE = 'POST_ADD_OFFICE_FAILURE';

export const POST_ADD_DEPARTMENT = 'POST_ADD_DEPARTMENT';
export const POST_ADD_DEPARTMENT_SUCCESS = 'POST_ADD_DEPARTMENT_SUCCESS';
export const POST_ADD_DEPARTMENT_FAILURE = 'POST_ADD_DEPARTMENT_FAILURE';

export const DELETE_OFFICE = 'DELETE_OFFICE';
export const DELETE_OFFICE_SUCCESS = 'DELETE_OFFICE_SUCCESS';
export const DELETE_OFFICE_FAILURE = 'DELETE_OFFICE_FAILURE';

export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILURE = 'DELETE_DEPARTMENT_FAILURE';

export const POST_EDIT_ORGANIZATION = 'POST_EDIT_ORGANIZATION';
export const POST_EDIT_ORGANIZATION_SUCCESS = 'POST_EDIT_ORGANIZATION_SUCCESS';
export const POST_EDIT_ORGANIZATION_FAILURE = 'POST_EDIT_ORGANIZATION_FAILURE';

export const POST_ASSOCIATE_REGISTER = 'POST_ASSOCIATE_REGISTER';
export const POST_ASSOCIATE_REGISTER_SUCCESS = 'POST_ASSOCIATE_REGISTER_SUCCESS';
export const POST_ASSOCIATE_REGISTER_FAILURE = 'POST_ASSOCIATE_REGISTER_FAILURE';

export const POST_ASSOCIATE_DOCUMENT_UPLOAD = 'POST_ASSOCIATE_DOCUMENT_UPLOAD';
export const POST_ASSOCIATE_DOCUMENT_UPLOAD_SUCCESS = 'POST_ASSOCIATE_DOCUMENT_UPLOAD_SUCCESS';
export const POST_ASSOCIATE_DOCUMENT_UPLOAD_FAILURE = 'POST_ASSOCIATE_DOCUMENT_UPLOAD_FAILURE';

export const POST_ADMIN_ADDITIONAL_INFO = 'POST_ADMIN_ADDITIONAL_INFO';
export const POST_ADMIN_ADDITIONAL_INFO_SUCCESS = 'POST_ADMIN_ADDITIONAL_INFO_SUCCESS';
export const POST_ADMIN_ADDITIONAL_INFO_FAILURE = 'POST_ADMIN_ADDITIONAL_INFO_FAILURE';

export const POST_ADMIN_REJECT_ASSOCIATE = 'POST_ADMIN_REJECT_ASSOCIATE';
export const POST_ADMIN_REJECT_ASSOCIATE_SUCCESS = 'POST_ADMIN_REJECT_ASSOCIATE_SUCCESS';
export const POST_ADMIN_REJECT_ASSOCIATE_FAILURE = 'POST_ADMIN_REJECT_ASSOCIATE_FAILURE';

export const POST_ADMIN_PRINT_AGREEMENT = 'POST_ADMIN_PRINT_AGREEMENT';
export const POST_ADMIN_PRINT_AGREEMENT_SUCCESS = 'POST_ADMIN_PRINT_AGREEMENT_SUCCESS';
export const POST_ADMIN_PRINT_AGREEMENT_FAILURE = 'POST_ADMIN_PRINT_AGREEMENT_FAILURE';

export const POST_RESEND_EMAIL_LINK = 'POST_RESEND_EMAIL_LINK';
export const POST_RESEND_EMAIL_LINK_SUCCESS = 'POST_RESEND_EMAIL_LINK_SUCCESS';
export const POST_RESEND_EMAIL_LINK_FAILURE = 'POST_RESEND_EMAIL_LINK_FAILURE';




export const POST_FILTERS = 'POST_FILTERS';
export const POST_FILTERS_SUCCESS = 'POST_FILTERS_SUCCESS';
export const POST_FILTERS_FAILURE = 'POST_FILTERS_FAILURE';


// PROPOSAL_MANAGEMENT

export const GET_VIEW_PROPOSALS = 'GET_VIEW_PROPOSALS';
export const GET_VIEW_PROPOSALS_SUCCESS = 'GET_VIEW_PROPOSALS_SUCCESS';
export const GET_VIEW_PROPOSALS_FAILURE = 'GET_VIEW_PROPOSALS_FAILURE';

