// GET CALLS 
export const GET_STATIC_DATA_PRODUCT = 'GET_STATIC_DATA_PRODUCT';
export const GET_STATIC_DATA_PRODUCT_SUCCESS = 'GET_STATIC_DATA_PRODUCT_SUCCESS';
export const GET_STATIC_DATA_PRODUCT_FAILURE = 'GET_STATIC_DATA_PRODUCT_FAILURE';

export const GET_STATIC_DATA_MANAGE_PRODUCT = 'GET_STATIC_DATA_MANAGE_PRODUCT';
export const GET_STATIC_DATA_MANAGE_PRODUCT_SUCCESS = 'GET_STATIC_DATA_MANAGE_PRODUCT_SUCCESS';
export const GET_STATIC_DATA_MANAGE_PRODUCT_FAILURE = 'GET_STATIC_DATA_MANAGE_PRODUCT_FAILURE';

export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
export const GET_PRODUCT_LIST_FAILURE = 'GET_PRODUCT_LIST_FAILURE';

export const GET_PRODUCT_DATA = 'GET_PRODUCT_DATA';
export const GET_PRODUCT_DATA_SUCCESS = 'GET_PRODUCT_DATA_SUCCESS';
export const GET_PRODUCT_DATA_FAILURE = 'GET_PRODUCT_DATA_FAILURE';

export const GET_WAREHOUSE_LIST = 'GET_WAREHOUSE_LIST';
export const GET_WAREHOUSE_LIST_SUCCESS = 'GET_WAREHOUSE_LIST_SUCCESS';
export const GET_WAREHOUSE_LIST_FAILURE = 'GET_WAREHOUSE_LIST_FAILURE';

export const GET_WAREHOUSE_DATA = 'GET_WAREHOUSE_DATA';
export const GET_WAREHOUSE_DATA_SUCCESS = 'GET_WAREHOUSE_DATA_SUCCESS';
export const GET_WAREHOUSE_DATA_FAILURE = 'GET_WAREHOUSE_DATA_FAILURE';

export const GET_VIEW_WAREHOUSE_DATA = 'GET_VIEW_WAREHOUSE_DATA';
export const GET_VIEW_WAREHOUSE_DATA_SUCCESS = 'GET_VIEW_WAREHOUSE_DATA_SUCCESS';
export const GET_VIEW_WAREHOUSE_DATA_FAILURE = 'GET_VIEW_WAREHOUSE_DATA_FAILURE';

export const GET_SUPPLIER_LIST = 'GET_SUPPLIER_LIST';
export const GET_SUPPLIER_LIST_SUCCESS = 'GET_SUPPLIER_LIST_SUCCESS';
export const GET_SUPPLIER_LIST_FAILURE = 'GET_SUPPLIER_LIST_FAILURE';

export const GET_SUPPLIER_DATA = 'GET_SUPPLIER_DATA';
export const GET_SUPPLIER_DATA_SUCCESS = 'GET_SUPPLIER_DATA_SUCCESS';
export const GET_SUPPLIER_DATA_FAILURE = 'GET_SUPPLIER_DATA_FAILURE';

export const GET_VIEW_SUPPLIER_DATA = 'GET_VIEW_SUPPLIER_DATA';
export const GET_VIEW_SUPPLIER_DATA_SUCCESS = 'GET_VIEW_SUPPLIER_DATA_SUCCESS';
export const GET_VIEW_SUPPLIER_DATA_FAILURE = 'GET_VIEW_SUPPLIER_DATA_FAILURE';

export const GET_PURCHASE_ORDER_LIST = 'GET_PURCHASE_ORDER_LIST';
export const GET_PURCHASE_ORDER_LIST_SUCCESS = 'GET_PURCHASE_ORDER_LIST_SUCCESS';
export const GET_PURCHASE_ORDER_LIST_FAILURE = 'GET_PURCHASE_ORDER_LIST_FAILURE';

export const SET_ALERT_STATUS = 'SET_ALERT_STATUS';
export const SET_ALERT_STATUS_SUCCESS = 'SET_ALERT_STATUS_SUCCESS';

export const GET_MODULE_LIST = 'GET_MODULE_LIST';
export const GET_MODULE_LIST_SUCCESS = 'GET_MODULE_LIST_SUCCESS';
export const GET_MODULE_LIST_FAILURE = 'GET_MODULE_LIST_FAILURE';

export const GET_MODULE_MAPPING_DATA = 'GET_MODULE_MAPPING_DATA';
export const GET_MODULE_MAPPING_DATA_SUCCESS = 'GET_MODULE_MAPPING_DATA_SUCCESS';
export const GET_MODULE_MAPPING_DATA_FAILURE = 'GET_MODULE_MAPPING_DATA_FAILURE';

export const GET_PRODUCT_PARTS = 'GET_PRODUCT_PARTS';
export const GET_PRODUCT_PARTS_SUCCESS = 'GET_PRODUCT_PARTS_SUCCESS';
export const GET_PRODUCT_PARTS_FAILURE = 'GET_PRODUCT_PARTS_FAILURE';

export const GET_PRODUCT_MODULE_MAPPING = 'GET_PRODUCT_MODULE_MAPPING';
export const GET_PRODUCT_MODULE_MAPPING_SUCCESS = 'GET_PRODUCT_MODULE_MAPPING_SUCCESS';
export const GET_PRODUCT_MODULE_MAPPING_FAILURE = 'GET_PRODUCT_MODULE_MAPPING_FAILURE';

export const GET_INVERTER_LIST = 'GET_INVERTER_LIST';
export const GET_INVERTER_LIST_SUCCESS = 'GET_INVERTER_LIST_SUCCESS';
export const GET_INVERTER_LIST_FAILURE = 'GET_INVERTER_LIST_FAILURE';

export const GET_OPTIMIZER_LIST = 'GET_OPTIMIZER_LIST';
export const GET_OPTIMIZER_LIST_SUCCESS = 'GET_OPTIMIZER_LIST_SUCCESS';
export const GET_OPTIMIZER_LIST_FAILURE = 'GET_OPTIMIZER_LIST_FAILURE';

export const GET_PRODUCT_PART_LIST = 'GET_PRODUCT_PART_LIST';
export const GET_PRODUCT_PART_LIST_SUCCESS = 'GET_PRODUCT_PART_LIST_SUCCESS';
export const GET_PRODUCT_PART_LIST_FAILURE = 'GET_PRODUCT_PART_LIST_FAILURE';

export const GET_OTHER_PRICE_CONFIG_FIELDS = 'GET_OTHER_PRICE_CONFIG_FIELDS';
export const GET_OTHER_PRICE_CONFIG_FIELDS_SUCCESS = 'GET_OTHER_PRICE_CONFIG_FIELDS_SUCCESS';
export const GET_OTHER_PRICE_CONFIG_FIELDS_FAILURE = 'GET_OTHER_PRICE_CONFIG_FIELDS_FAILURE';

export const GET_CONFIG_FIELDS_LIST = 'GET_CONFIG_FIELDS_LIST';
export const GET_CONFIG_FIELDS_LIST_SUCCESS = 'GET_CONFIG_FIELDS_LIST_SUCCESS';
export const GET_CONFIG_FIELDS_LIST_FAILURE = 'GET_CONFIG_FIELDS_LIST_FAILURE';

export const GET_STATIC_DATA_PURCHASE_ORDER = 'GET_STATIC_DATA_PURCHASE_ORDER';
export const GET_STATIC_DATA_PURCHASE_ORDER_SUCCESS = 'GET_STATIC_DATA_PURCHASE_ORDER_SUCCESS';
export const GET_STATIC_DATA_PURCHASE_ORDER_FAILURE = 'GET_STATIC_DATA_PURCHASE_ORDER_FAILURE';

export const GET_PO_SUPPLIER_LIST = 'GET_PO_SUPPLIER_LIST';
export const GET_PO_SUPPLIER_LIST_SUCCESS = 'GET_PO_SUPPLIER_LIST_SUCCESS';
export const GET_PO_SUPPLIER_LIST_FAILURE = 'GET_PO_SUPPLIER_LIST_FAILURE';

// POST CALLS BELOW
export const POST_ADD_PRODUCT = 'POST_ADD_PRODUCT';
export const POST_ADD_PRODUCT_SUCCESS = 'POST_ADD_PRODUCT_SUCCESS';
export const POST_ADD_PRODUCT_FAILURE = 'POST_ADD_PRODUCT_FAILURE';

export const POST_EDIT_PRODUCT = 'POST_EDIT_PRODUCT';
export const POST_EDIT_PRODUCT_SUCCESS = 'POST_EDIT_PRODUCT_SUCCESS';
export const POST_EDIT_PRODUCT_FAILURE = 'POST_EDIT_PRODUCT_FAILURE';

export const POST_SEARCH_PRODUCTS = 'POST_SEARCH_PRODUCTS';
export const POST_SEARCH_PRODUCTS_SUCCESS = 'POST_SEARCH_PRODUCTS_SUCCESS';
export const POST_SEARCH_PRODUCTS_FAILURE = 'POST_SEARCH_PRODUCTS_FAILURE';

export const POST_FILTER_PRODUCTS = 'POST_FILTER_PRODUCTS';
export const POST_FILTER_PRODUCTS_SUCCESS = 'POST_FILTER_PRODUCTS_SUCCESS';
export const POST_FILTER_PRODUCTS_FAILURE = 'POST_FILTER_PRODUCTS_FAILURE';

export const POST_DELETE_PRODUCT = 'POST_DELETE_PRODUCT';
export const POST_DELETE_PRODUCT_SUCCESS = 'POST_DELETE_PRODUCT_SUCCESS';
export const POST_DELETE_PRODUCT_FAILURE ='POST_DELETE_PRODUCT_FAILURE';

export const POST_SUBMIT_MAPPING = 'POST_SUBMIT_MAPPING';
export const POST_SUBMIT_MAPPING_SUCCESS = 'POST_SUBMIT_MAPPING_SUCCESS';
export const POST_SUBMIT_MAPPING_FAILURE = 'POST_SUBMIT_MAPPING_FAILURE';

export const POST_SEARCH_WAREHOUSE = 'POST_SEARCH_WAREHOUSE';
export const POST_SEARCH_WAREHOUSE_SUCCESS = 'POST_SEARCH_WAREHOUSE_SUCCESS';
export const POST_SEARCH_WAREHOUSE_FAILURE = 'POST_SEARCH_WAREHOUSE_FAILURE';

export const POST_FILTER_WAREHOUSE = 'POST_FILTER_WAREHOUSE';
export const POST_FILTER_WAREHOUSE_SUCCESS = 'POST_FILTER_WAREHOUSE_SUCCESS';
export const POST_FILTER_WAREHOUSE_FAILURE = 'POST_FILTER_WAREHOUSE_FAILURE';

export const POST_DELETE_WAREHOUSE = 'POST_DELETE_WAREHOUSE';
export const POST_DELETE_WAREHOUSE_SUCCESS = 'POST_DELETE_WAREHOUSE_SUCCESS';
export const POST_DELETE_WAREHOUSE_FAILURE = 'POST_DELETE_WAREHOUSE_FAILURE';

export const POST_ADD_WAREHOUSE = 'POST_ADD_WAREHOUSE';
export const POST_ADD_WAREHOUSE_SUCCESS = 'POST_ADD_WAREHOUSE_SUCCESS';
export const POST_ADD_WAREHOUSE_FAILURE = 'POST_ADD_WAREHOUSE_FAILURE';

export const POST_EDIT_WAREHOUSE = 'POST_EDIT_WAREHOUSE';
export const POST_EDIT_WAREHOUSE_SUCCESS = 'POST_EDIT_WAREHOUSE_SUCCESS';
export const POST_EDIT_WAREHOUSE_FAILURE = 'POST_EDIT_WAREHOUSE_FAILURE';

export const POST_SEARCH_SUPPLIER = 'POST_SEARCH_SUPPLIER';
export const POST_SEARCH_SUPPLIER_SUCCESS = 'POST_SEARCH_SUPPLIER_SUCCESS';
export const POST_SEARCH_SUPPLIER_FAILURE = 'POST_SEARCH_SUPPLIER_FAILURE';

export const POST_FILTER_SUPPLIER = 'POST_FILTER_SUPPLIER';
export const POST_FILTER_SUPPLIER_SUCCESS = 'POST_FILTER_SUPPLIER_SUCCESS';
export const POST_FILTER_SUPPLIER_FAILURE = 'POST_FILTER_SUPPLIER_FAILURE';

export const POST_DELETE_SUPPLIER = 'POST_DELETE_SUPPLIER';
export const POST_DELETE_SUPPLIER_SUCCESS = 'POST_DELETE_SUPPLIER_SUCCESS';
export const POST_DELETE_SUPPLIER_FAILURE = 'POST_DELETE_SUPPLIER_FAILURE';

export const POST_ADD_SUPPLIER = 'POST_ADD_SUPPLIER';
export const POST_ADD_SUPPLIER_SUCCESS = 'POST_ADD_SUPPLIER_SUCCESS';
export const POST_ADD_SUPPLIER_FAILURE = 'POST_ADD_SUPPLIER_FAILURE';

export const POST_EDIT_SUPPLIER = 'POST_EDIT_SUPPLIER';
export const POST_EDIT_SUPPLIER_SUCCESS = 'POST_EDIT_SUPPLIER_SUCCESS';
export const POST_EDIT_SUPPLIER_FAILURE = 'POST_EDIT_SUPPLIER_FAILURE';

export const POST_SEARCH_PURCHASE_ORDER = 'POST_SEARCH_PURCHASE_ORDER';
export const POST_SEARCH_PURCHASE_ORDER_SUCCESS = 'POST_SEARCH_PURCHASE_ORDER_SUCCESS';
export const POST_SEARCH_PURCHASE_ORDER_FAILURE = 'POST_SEARCH_PURCHASE_ORDER_FAILURE';

export const POST_FILTER_PURCHASE_ORDER = 'POST_FILTER_PURCHASE_ORDER';
export const POST_FILTER_PURCHASE_ORDER_SUCCESS = 'POST_FILTER_PURCHASE_ORDER_SUCCESS';
export const POST_FILTER_PURCHASE_ORDER_FAILURE = 'POST_FILTER_PURCHASE_ORDER_FAILURE';

export const POST_DELETE_PURCHASE_ORDER = 'POST_DELETE_PURCHASE_ORDER';
export const POST_DELETE_PURCHASE_ORDER_SUCCESS = 'POST_DELETE_PURCHASE_ORDER_SUCCESS';
export const POST_DELETE_PURCHASE_ORDER_FAILURE = 'POST_DELETE_PURCHASE_ORDER_FAILURE';

export const POST_CREATE_PURCHASE_ORDER = 'POST_CREATE_PURCHASE_ORDER';
export const POST_CREATE_PURCHASE_ORDER_SUCCESS = 'POST_CREATE_PURCHASE_ORDER_SUCCESS';
export const POST_CREATE_PURCHASE_ORDER_FAILURE = 'POST_CREATE_PURCHASE_ORDER_FAILURE';

export const POST_PRODUCT_IMAGE_UPLOAD = 'POST_PRODUCT_IMAGE_UPLOAD';
export const POST_PRODUCT_IMAGE_UPLOAD_SUCCESS = 'POST_PRODUCT_IMAGE_UPLOAD_SUCCESS';
export const POST_PRODUCT_IMAGE_UPLOAD_FAILURE = 'POST_PRODUCT_IMAGE_UPLOAD_FAILURE';

export const POST_ADD_CONFIGURATION_FIELDS = 'POST_ADD_CONFIGURATION_FIELDS';
export const POST_ADD_CONFIGURATION_FIELDS_SUCCESS = 'POST_ADD_CONFIGURATION_FIELDS_SUCCESS';
export const POST_ADD_CONFIGURATION_FIELDS_FAILURE = 'POST_ADD_CONFIGURATION_FIELDS_FAILURE';

export const POST_EDIT_CONFIG_FIELDS = 'POST_EDIT_CONFIG_FIELDS';
export const POST_EDIT_CONFIG_FIELDS_SUCCESS = 'POST_EDIT_CONFIG_FIELDS_SUCCESS';
export const POST_EDIT_CONFIG_FIELDS_FAILURE = 'POST_EDIT_CONFIG_FIELDS_FAILURE';

export const POST_DELETE_CONFIG_FIELDS = 'POST_DELETE_CONFIG_FIELDS';
export const POST_DELETE_CONFIG_FIELDS_SUCCESS = 'POST_DELETE_CONFIG_FIELDS_SUCCESS';
export const POST_DELETE_CONFIG_FIELDS_FAILURE = 'POST_DELETE_CONFIG_FIELDS_FAILURE';

export const POST_SEARCH_CONFIG_FIELDS = 'POST_SEARCH_CONFIG_FIELDS';
export const POST_SEARCH_CONFIG_FIELDS_SUCCESS = 'POST_SEARCH_CONFIG_FIELDS_SUCCESS';
export const POST_SEARCH_CONFIG_FIELDS_FAILURE = 'POST_SEARCH_CONFIG_FIELDS_FAILURE';

export const POST_EXPORT_INVENTORY = 'POST_EXPORT_INVENTORY';
export const POST_EXPORT_INVENTORY_SUCCESS = 'POST_EXPORT_INVENTORY_SUCCESS';
export const POST_EXPORT_INVENTORY_FAILURE = 'POST_EXPORT_INVENTORY_FAILURE';


