// POST CALLS BELOW
export const POST_EDIT_PROFILE = 'POST_EDIT_PROFILE';
export const POST_EDIT_PROFILE_SUCCESS = 'POST_EDIT_PROFILE_SUCCESS';
export const POST_EDIT_PROFILE_FAILURE = 'POST_EDIT_PROFILE_FAILURE';

export const POST_CHANGE_PASSWORD = 'POST_CHANGE_PASSWORD';
export const POST_CHANGE_PASSWORD_SUCCESS = 'POST_CHANGE_PASSWORD_SUCCESS';
export const POST_CHANGE_PASSWORD_FAILURE = 'POST_CHANGE_PASSWORD_FAILURE';

export const POST_PROFILE_IMAGE_UPLOAD = 'POST_PROFILE_IMAGE_UPLOAD';
export const POST_PROFILE_IMAGE_UPLOAD_SUCCESS = 'POST_PROFILE_IMAGE_UPLOAD_SUCCESS';
export const POST_PROFILE_IMAGE_UPLOAD_FAILURE = 'POST_PROFILE_IMAGE_UPLOAD_FAILURE';