export const GET_VIEW_PROPOSALS        = 'GET_VIEW_PROPOSALS';
export const GET_VIEW_PROPOSALS_SUCCESS = 'GET_VIEW_PROPOSALS_SUCCESS';
export const GET_VIEW_PROPOSALS_FAILURE = 'GET_VIEW_PROPOSALS_FAILURE';

export const DELETE_PROPOSAL = 'DELETE_PROPOSAL';
export const DELETE_PROPOSAL_SUCCESS = 'DELETE_PROPOSAL_SUCCESS';
export const DELETE_PROPOSAL_FAILURE = 'DELETE_PROPOSAL_FAILURE';

export const PROPOSAL_DETAILS = 'PROPOSAL_DETAILS';
export const PROPOSAL_DETAILS_SUCCESS = 'PROPOSAL_DETAILS_SUCCESS';
export const PROPOSAL_DETAILS_FAILURE = 'PROPOSAL_DETAILS_FAILURE';

export const POST_SEARCH_PROPOSALS        = 'POST_SEARCH_PROPOSALS';
export const POST_SEARCH_PROPOSALS_SUCCESS = 'POST_SEARCH_PROPOSALS_SUCCESS';
export const POST_SEARCH_PROPOSALS_FAILURE = 'POST_SEARCH_PROPOSALS_FAILURE';

export const PATCH_UPDATE_PROPOSAL        = 'PATCH_UPDATE_PROPOSAL';
export const PATCH_UPDATE_PROPOSAL_SUCCESS = 'PATCH_UPDATE_PROPOSAL_SUCCESS';
export const PATCH_UPDATE_PROPOSAL_FAILURE = 'PATCH_UPDATE_PROPOSAL_FAILURE';

export const GET_PROPOSAL_PROGRESS        = 'GET_PROPOSAL_PROGRESS';
export const GET_PROPOSAL_PROGRESS_SUCCESS = 'GET_PROPOSAL_PROGRESS_SUCCESS';
export const GET_PROPOSAL_PROGRESS_FAILURE = 'GET_PROPOSAL_PROGRESS_FAILURE';
