// GET METHODS
export const GET_PURCHASE_PLAN_LIST = 'GET_PURCHASE_PLAN_LIST';
export const GET_PURCHASE_PLAN_LIST_SUCCESS = 'GET_PURCHASE_PLAN_LIST_SUCCESS';
export const GET_PURCHASE_PLAN_LIST_FAILURE = 'GET_PURCHASE_PLAN_LIST_FAILURE';

export const GET_STATIC_DATA_PURCHASE_PLAN = 'GET_STATIC_DATA_PURCHASE_PLAN';
export const GET_STATIC_DATA_PURCHASE_PLAN_SUCCESS = 'GET_STATIC_DATA_PURCHASE_PLAN_SUCCESS';
export const GET_STATIC_DATA_PURCHASE_PLAN_FAILURE = 'GET_STATIC_DATA_PURCHASE_PLAN_FAILURE';

export const GET_PURCHASE_PLAN_DATA = 'GET_PURCHASE_PLAN_DATA';
export const GET_PURCHASE_PLAN_DATA_SUCCESS = 'GET_PURCHASE_PLAN_DATA_SUCCESS';
export const GET_PURCHASE_PLAN_DATA_FAILURE  = 'GET_PURCHASE_PLAN_DATA_FAILURE';

export const GET_STATIC_DATA_CONFIG = 'GET_STATIC_DATA_CONFIG';
export const GET_STATIC_DATA_CONFIG_SUCCESS = 'GET_STATIC_DATA_CONFIG_SUCCESS';
export const GET_STATIC_DATA_CONFIG_FAILURE = 'GET_STATIC_DATA_CONFIG_FAILURE';

// POST METHODS
export const POST_SEARCH_PURCHASE_PLAN = 'POST_SEARCH_PURCHASE_PLAN';
export const POST_SEARCH_PURCHASE_PLAN_SUCCESS = 'POST_SEARCH_PURCHASE_PLAN_SUCCESS';
export const POST_SEARCH_PURCHASE_PLAN_FAILURE = 'POST_SEARCH_PURCHASE_PLAN_FAILURE';

export const POST_FILTER_PURCHASE_PLAN = 'POST_FILTER_PURCHASE_PLAN';
export const POST_FILTER_PURCHASE_PLAN_SUCCESS = 'POST_FILTER_PURCHASE_PLAN_SUCCESS';
export const POST_FILTER_PURCHASE_PLAN_FAILURE = 'POST_FILTER_PURCHASE_PLAN_FAILURE';

export const POST_DELETE_PURCHASE_PLAN = 'POST_DELETE_PURCHASE_PLAN';
export const POST_DELETE_PURCHASE_PLAN_SUCCESS = 'POST_DELETE_PURCHASE_PLAN_SUCCESS';
export const POST_DELETE_PURCHASE_PLAN_FAILURE = 'POST_DELETE_PURCHASE_PLAN_FAILURE';

export const POST_ADD_PURCHASE_PLAN = 'POST_ADD_PURCHASE_PLAN';
export const POST_ADD_PURCHASE_PLAN_SUCCESS = 'POST_ADD_PURCHASE_PLAN_SUCCESS';
export const POST_ADD_PURCHASE_PLAN_FAILURE = 'POST_ADD_PURCHASE_PLAN_FAILURE';

export const POST_EDIT_PURCHASE_PLAN = 'POST_EDIT_PURCHASE_PLAN';
export const POST_EDIT_PURCHASE_PLAN_SUCCESS = 'POST_EDIT_PURCHASE_PLAN_SUCCESS';
export const POST_EDIT_PURCHASE_PLAN_FAILURE = 'POST_EDIT_PURCHASE_PLAN_FAILURE';