const INVENTORY_MANAGEMENT_API = '/internal-api/inventoryManagement';
const INTERNALAPI = {
    // GET METHODS
    GET_STATIC_DATA_MANAGE_PRODUCT: `${INVENTORY_MANAGEMENT_API}/staticDataProductList`,
    GET_PRODUCT_LIST: `${INVENTORY_MANAGEMENT_API}/productList`,
    GET_STATIC_DATA_PRODUCT: `${INVENTORY_MANAGEMENT_API}/staticDataProduct`,
    GET_PRODUCT_DATA: `${INVENTORY_MANAGEMENT_API}/productData`,
    GET_MODULE_LIST: `${INVENTORY_MANAGEMENT_API}/moduleList`,
    GET_MODULE_MAPPING_DATA: `${INVENTORY_MANAGEMENT_API}/moduleMappingData`,
    GET_PRODUCT_PARTS: `${INVENTORY_MANAGEMENT_API}/productParts`,
    GET_PRODUCT_MODULE_MAPPING: `${INVENTORY_MANAGEMENT_API}/viewModuleMapping`,
    GET_INVERTER_LIST: `${INVENTORY_MANAGEMENT_API}/inverterList`,
    GET_OPTIMIZER_LIST: `${INVENTORY_MANAGEMENT_API}/optimizerList`,
    GET_PRODUCT_PART_LIST: `${INVENTORY_MANAGEMENT_API}/productPartList`,

    GET_WAREHOUSE_LIST: `${INVENTORY_MANAGEMENT_API}/warehouseList`,
    GET_WAREHOUSE_DATA: `${INVENTORY_MANAGEMENT_API}/warehouseData`,
    GET_VIEW_WAREHOUSE_DATA: `${INVENTORY_MANAGEMENT_API}/warehouseData`,

    GET_SUPPLIER_LIST: `${INVENTORY_MANAGEMENT_API}/supplierList`,
    GET_SUPPLIER_DATA: `${INVENTORY_MANAGEMENT_API}/supplierData`,
    GET_VIEW_SUPPLIER_DATA: `${INVENTORY_MANAGEMENT_API}/supplierData`,

    GET_PURCHASE_ORDER_LIST: `${INVENTORY_MANAGEMENT_API}/purchaseOrderList`,
    GET_STATIC_DATA_PURCHASE_ORDER: `${INVENTORY_MANAGEMENT_API}/staticDataPurchaseOrder`,
    GET_PO_SUPPLIER_LIST: `${INVENTORY_MANAGEMENT_API}/poSupplierList`,

    GET_OTHER_PRICE_CONFIG_FIELDS: `${INVENTORY_MANAGEMENT_API}/otherPriceConfigFields`,
    GET_CONFIG_FIELDS_LIST: `${INVENTORY_MANAGEMENT_API}/configFieldsList`,

    //POST METHODS
    POST_SEARCH_PRODUCTS: `${INVENTORY_MANAGEMENT_API}/searchProducts`,
    POST_FILTER_PRODUCTS: `${INVENTORY_MANAGEMENT_API}/filterProducts`,
    POST_ADD_PRODUCT: `${INVENTORY_MANAGEMENT_API}/product`,
    POST_DELETE_PRODUCT: `${INVENTORY_MANAGEMENT_API}/deleteProduct`,
    POST_PRODUCT_IMAGE_UPLOAD: `${INVENTORY_MANAGEMENT_API}/productImageUpload`,
    POST_EDIT_PRODUCT: `${INVENTORY_MANAGEMENT_API}/editProduct`,
    POST_SUBMIT_MAPPING: `${INVENTORY_MANAGEMENT_API}/submitMapping`,

    POST_SEARCH_WAREHOUSE: `${INVENTORY_MANAGEMENT_API}/searchWarehouse`,
    POST_FILTER_WAREHOUSE: `${INVENTORY_MANAGEMENT_API}/filterWarehouse`,
    POST_DELETE_WAREHOUSE: `${INVENTORY_MANAGEMENT_API}/deleteWarehouse`,
    POST_ADD_WAREHOUSE: `${INVENTORY_MANAGEMENT_API}/addWarehouse`,
    POST_EDIT_WAREHOUSE: `${INVENTORY_MANAGEMENT_API}/editWarehouse`,

    POST_SEARCH_SUPPLIER: `${INVENTORY_MANAGEMENT_API}/searchSupplier`,
    POST_FILTER_SUPPLIER: `${INVENTORY_MANAGEMENT_API}/filterSupplier`,
    POST_DELETE_SUPPLIER: `${INVENTORY_MANAGEMENT_API}/deleteSupplier`,
    POST_ADD_SUPPLIER: `${INVENTORY_MANAGEMENT_API}/addSupplier`,
    POST_EDIT_SUPPLIER: `${INVENTORY_MANAGEMENT_API}/editSupplier`,

    POST_SEARCH_PURCHASE_ORDER: `${INVENTORY_MANAGEMENT_API}/searchPurchaseOrder`,
    POST_FILTER_PURCHASE_ORDER: `${INVENTORY_MANAGEMENT_API}/filterPurchaseOrder`,
    POST_DELETE_PURCHASE_ORDER: `${INVENTORY_MANAGEMENT_API}/deletePurchaseOrder`,
    POST_CREATE_PURCHASE_ORDER: `${INVENTORY_MANAGEMENT_API}/createPurchaseOrder`,

    POST_ADD_CONFIGURATION_FIELDS: `${INVENTORY_MANAGEMENT_API}/addConfigurationFields`,
    POST_EDIT_CONFIG_FIELDS: `${INVENTORY_MANAGEMENT_API}/editConfigFields`,
    POST_DELETE_CONFIG_FIELDS: `${INVENTORY_MANAGEMENT_API}/deleteConfigFields`,
    POST_SEARCH_CONFIG_FIELDS: `${INVENTORY_MANAGEMENT_API}/searchConfigFields`
};

export default INTERNALAPI;